[package]
name = "curses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pancurses = {version="0.17.0", features=["win32"]}
crossbeam = "0.8.1"
rand = "0.8.4"